### ISSUE TITLE
Question: Unclear how connections can be removed

### ISSUE THREAD

**Issue by atoav** [haighcam/egui_nodes#7]
First of all thanks for the great work! Maybe it is just me, but I wasn't able to figure out how to remove connections. I tried dragging them "away", rightclicking, "cutting" them off with all kind of modifier + click combinations etc.

Is this just not implemented yet, or am I missing something here?

**Comment by comcloudway** [comment]
I found a solution whilst browsing [the pw-viz source code](https://github.com/Ax9D/pw-viz/blob/main/src/ui/graph.rs) (not by me - just found it when looking for examples)

Apparently you can configure the context to allow node removal, by dragging the connection:
```rust
let mut context = egui_nodes::Context::default()
// configures the link drag to remove feature
context.attribute_flag_push(egui_nodes::AttributeFlags::EnableLinkDetachWithDragClick);
```
I'm using configuring it like this in my project and it works for me.

I just noticed that this flag is documented [here](https://docs.rs/egui_nodes/0.1.3/egui_nodes/enum.AttributeFlags.html#variant.EnableLinkDetachWithDragClick)

EDIT: Added reference to docs

**Comment by atoav** [comment]
This can be closed then
